// Auto-generated by OpenLane
module brownout_dig(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[2:0] otrip,
  input[2:0] vtrip,
  input ena,
  input force_ena_rc_osc,
  input force_dis_rc_osc,
  input force_short_oneshot,
  input dcomp,
  input brout_filt,
  input osc_ck,
  output osc_ena,
  output outb_unbuf,
  output[7:0] otrip_decoded,
  output[7:0] vtrip_decoded,
  output timed_out
);
endmodule
